### ISSUE TITLE
怎么让所有的「back」按钮都跳转到home页？

### ISSUE THREAD

**Issue by zxmio** [hi-caicai/farbox-theme-cais#1]
如果是复制一篇文章的链接单独打开，左上角的「back」按钮是失效的，相当于我没有了一个回到主页的入口。

我看button代码的设定是 "window.history.go(-1)") ，请问怎么设置才能在所有情况下的「back」按钮都能跳回home页？

@hi-caicai

**Comment by hi-caicai** [comment]
@xuanmingzhang 我去看代码的时候，发现这个back 早就拿掉了呢？比如： http://cais.cai-cai.me/post/2015-05-22 你的是什么时候代码呢？

**Comment by zxmio** [comment]
@hi-caicai 用的就是你现在仓库的代码呀。在farbox后台设置「日志URL格式」为 `/<url>` ，post页面就会显示back了。如果是 `/post/<url>` 格式，就是 http://cais.cai-cai.me/post/2015-05-22 的样子。
![farbox-url](https://cloud.githubusercontent.com/assets/11482563/18522940/b710564a-7ae4-11e6-86e5-6f4be96e013f.jpg)

![example-farbox](https://cloud.githubusercontent.com/assets/11482563/18522952/bd93321c-7ae4-11e6-93aa-94333947e7eb.jpg)

**Comment by hi-caicai** [comment]
@xuanmingzhang 这个估计是你下到的老版本，用 github 的版本覆盖下

**Comment by zxmio** [comment]
@hi-caicai 我打包下载的是这个仓库：https://github.com/hi-caicai/farbox-theme-cais

**Comment by hi-caicai** [comment]
@xuanmingzhang 这样啊。那我更新下～ 稍等

**Comment by hi-caicai** [comment]
@xuanmingzhang done,下载新的版本，这样就没有 back 了

**Comment by zxmio** [comment]
@hi-caicai 感谢！晚上回去覆盖试试，中秋快乐！
